# Generated by Django 3.2.5 on 2021-07-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='likes',
        ),
    ]
