# Generated by Django 3.2.5 on 2021-07-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
    ]
