# Generated by Django 3.2.5 on 2021-07-27 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_blog', '0002_rename_post_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikes',
            old_name='post',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='post',
            new_name='article',
        ),
        migrations.AddField(
            model_name='dislikes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
