# Generated by Django 3.2.5 on 2021-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_blog', '0002_article_comment_dislikes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
