# Generated by Django 3.2.5 on 2021-07-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_blog', '0015_alter_article_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, default='images/dummy.png', null=True, upload_to=''),
        ),
    ]
